"""created new moon model and connected it to planets as a one to many relationship

Revision ID: 869792db1ef9
Revises: 6f5e2a46ca33
Create Date: 2025-05-07 21:50:59.854795

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '869792db1ef9'
down_revision = '6f5e2a46ca33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('moon',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['planet_id'], ['planet.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moon')
    # ### end Alembic commands ###
